# Site settings
title: Stay awhile and listen
email: kennethlarsen@fsfe.org
description: > # hacking for freedom
baseurl: "http://deckardcain.github.io" # the subpath of your site, e.g. /blog/
url: "http://deckardcain.github.io" # the base hostname & protocol for your site
twitter_username: kennethlarsen
github_username:  deckardcain

# Build settings
markdown: kramdown
